[2022-01-03 08:13:03,482] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: localExecutorTest.task2 2022-01-03T08:12:58.449194+00:00 [queued]>
[2022-01-03 08:13:03,504] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: localExecutorTest.task2 2022-01-03T08:12:58.449194+00:00 [queued]>
[2022-01-03 08:13:03,505] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 08:13:03,506] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-03 08:13:03,508] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 08:13:03,525] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task2> on 2022-01-03T08:12:58.449194+00:00
[2022-01-03 08:13:03,533] {standard_task_runner.py:52} INFO - Started process 1291491 to run task
[2022-01-03 08:13:03,556] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'localExecutorTest', 'task2', '2022-01-03T08:12:58.449194+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/localexecutorTest.py', '--cfg-path', '/tmp/tmpk5iqagrg', '--error-file', '/tmp/tmpdr5f50_p']
[2022-01-03 08:13:03,560] {standard_task_runner.py:77} INFO - Job 11: Subtask task2
[2022-01-03 08:13:03,705] {logging_mixin.py:104} INFO - Running <TaskInstance: localExecutorTest.task2 2022-01-03T08:12:58.449194+00:00 [running]> on host airflowvm
[2022-01-03 08:13:03,839] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=localExecutorTest
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T08:12:58.449194+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-03T08:12:58.449194+00:00
[2022-01-03 08:13:03,839] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-03 08:13:03,839] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-01-03 08:13:03,846] {subprocess.py:75} INFO - Output:
[2022-01-03 08:13:06,849] {subprocess.py:83} INFO - Command exited with return code 0
[2022-01-03 08:13:06,937] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=localExecutorTest, task_id=task2, execution_date=20220103T081258, start_date=20220103T081303, end_date=20220103T081306
[2022-01-03 08:13:07,005] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-03 08:13:07,037] {local_task_job.py:151} INFO - Task exited with return code 0
