[2022-01-03 08:12:59,303] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: localExecutorTest.task1 2022-01-03T08:12:58.449194+00:00 [queued]>
[2022-01-03 08:12:59,312] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: localExecutorTest.task1 2022-01-03T08:12:58.449194+00:00 [queued]>
[2022-01-03 08:12:59,312] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 08:12:59,312] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-03 08:12:59,313] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 08:12:59,327] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task1> on 2022-01-03T08:12:58.449194+00:00
[2022-01-03 08:12:59,329] {standard_task_runner.py:52} INFO - Started process 1291288 to run task
[2022-01-03 08:12:59,334] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'localExecutorTest', 'task1', '2022-01-03T08:12:58.449194+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/localexecutorTest.py', '--cfg-path', '/tmp/tmpkpylkiua', '--error-file', '/tmp/tmpzwu8qa6c']
[2022-01-03 08:12:59,335] {standard_task_runner.py:77} INFO - Job 10: Subtask task1
[2022-01-03 08:12:59,391] {logging_mixin.py:104} INFO - Running <TaskInstance: localExecutorTest.task1 2022-01-03T08:12:58.449194+00:00 [running]> on host airflowvm
[2022-01-03 08:12:59,457] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=localExecutorTest
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T08:12:58.449194+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-03T08:12:58.449194+00:00
[2022-01-03 08:12:59,458] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-03 08:12:59,459] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-01-03 08:12:59,464] {subprocess.py:75} INFO - Output:
[2022-01-03 08:13:02,467] {subprocess.py:83} INFO - Command exited with return code 0
[2022-01-03 08:13:02,507] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=localExecutorTest, task_id=task1, execution_date=20220103T081258, start_date=20220103T081259, end_date=20220103T081302
[2022-01-03 08:13:02,540] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2022-01-03 08:13:02,570] {local_task_job.py:151} INFO - Task exited with return code 0
